name: "model_train_1"
select_model: 9 # model.yaml 참고, 해당모델 index를 가져온다
dir_path: # 경로설정
  code: "/opt/ml/code/src"
  base: "/opt/ml/code/models"
  train_data_path: "/opt/ml/dataset/train/train.csv"
  test_data_path: "/opt/ml/dataset/test/test_data.csv"
  tokenizer: "tokenizer"
  model: "best_model"
  submission: "prediction/submission.csv"
model:
  num_labels: 30
  model_list:
    0: "monologg/koelectra-base-v3-discriminator"
    1: "HanBert-54kN-torch"
    2: "kykim/bert-kor-base"
    3: "monologg/koelectra-small-v3-discriminator"
    4: "monologg/kobert"
    5: "hyunwoongko/kobart"
    6: "kykim/electra-kor-base"
    7: "kykim/albert-kor-base"
    8: "kykim/funnel-kor-base"
    9: "klue/bert-base"
    10: "klue/roberta-large"
    11: "klue/roberta-base"
    12: "klue/roberta-small"
train_args:
  log: "logs"
  output: "results"
  batch_size: 128
  learning_rate: 5e-5
  weight_decay: 0.01
  num_train_epochs: 20
  warmup_steps: 500
  save_total_limit: 3
  save_steps: 500
  logging_steps: 100
  eval_steps: 500
  evaluation_strategy: "steps"
dataset:
  add_data: True # 추가 데이터 불러오기
  n_splits: 18 # K_fold 시 몇개의 데이터로 나눌것인가?
  num: 0 # K_fold로 나눈 데이터중 num번재 인덱스를 가져온다.
  shuffle: False # K_fold로 나눌때 섞는다. 이때 num은 작동하지 않는다
